name: auto-merge

on:
  workflow_dispatch:
    inputs:
      pr-number:
        required: true

jobs:
auto-merge:
  needs: ci_dev
  permissions:
    contents: write
    pull-requests: write
  runs-on: ubuntu-latest
  steps:
    - uses: fastify/github-action-merge-dependabot@v3.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        target: patch