name: auto-merge
on: [pull_request]
jobs:
  auto-merge:
    permissions:
      contents: write
      pull-requests: write
      approve-only: true
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: patch