name: Empty backport self-closing
on: [ pull_request ]
jobs:
  new-dependabot-pr:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'backport/')
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Self-closing
        uses: actions/github-script@v5
        with:
          script: |
            console.log("entró Daniela")

            //Close pull request
            const files = await github.rest.pulls.files({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.number }}
            })
            
            console.log(files)
